### ISSUE TITLE
Decide on authentication scheme for api.met.no

### ISSUE THREAD

**Issue by havardf** [metno/S-ENDA-project-plan#154]
What kind of authentication scheme to go for in the near future?
Alternatives:
- Official oidc login.met.no solution.
- Federated token-generation.
- Custom request header with client info on specific format.
- Keep on rollin with todays setup.

**Comment by geira** [comment]
If we define "near future" as the current year, our options are as follows:

- login.met.no will probably not be available until late in the year, and implementation on api.met.no is complicated and not feasible this year
- Federated token-generation doesn't seem to work as systems have problems validating tokens from others. Unfederated (local) token generation works in weatherapi but not proxy; will be lots of work and not condoned by The Powers That Be
- Custom request header (i.e. not using User-Agent nor Autentication headers): Not supported by Swagger UI and other tools; not recommended
- Keep on rollin with todays setup: Seems like the only feasible action, since we cannot change anything before launching locationforecast 2.0 and it will be very unpopular for people having to change again soon
